# generated by zon2nix (https://github.com/nix-community/zon2nix)

{
linkFarm,
fetchzip,
zig,
}:

linkFarm "zig-packages" [
  {
    name = "1220711bf931da6bb89b3fa695f56dd938a749de9830fa479d850c279e3f739388db";
    path = fetchzip {
      url = "https://github.com/Guigui220D/zig-sfml-wrapper/archive/bf012025c70be4c101717a9041ce55c776b58d4d.tar.gz";
      hash = "sha256-73Yx4PqON/nZjoFa1BR/tbx+kueYsBJztuqlhvLWViE=";
    };
  }
]
